// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtSzlGoeMhtBuRjBSfhBSapcyOPWSw6_Q',
    appId: '1:1021626298285:android:ca41c1db1db0aca3923b24',
    messagingSenderId: '1021626298285',
    projectId: 'healthcare-bf396',
    storageBucket: 'healthcare-bf396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBbmOZr7Hcft3ylSE1wlVSaBvjFIaGfVo',
    appId: '1:1021626298285:ios:000abd721bf8faa9923b24',
    messagingSenderId: '1021626298285',
    projectId: 'healthcare-bf396',
    storageBucket: 'healthcare-bf396.appspot.com',
    iosBundleId: 'suruch.boss.healthcare.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBbmOZr7Hcft3ylSE1wlVSaBvjFIaGfVo',
    appId: '1:1021626298285:ios:13439c0c51c3bc67923b24',
    messagingSenderId: '1021626298285',
    projectId: 'healthcare-bf396',
    storageBucket: 'healthcare-bf396.appspot.com',
    iosBundleId: 'suruch.boss.healthcare.healthcare.RunnerTests',
  );
}
